### ISSUE TITLE
Dati per Comune in Lombardia

### ISSUE THREAD

**Issue by nelsonmau** [floatingpurr/covid-19_ita_bot#1]
a [questo link](https://github.com/ondata/covid19italia/blob/master/webservices/regioneLombardia/README.md) @aborruso ha reso accessibili i dati per comune pubblicati da Regione Lombardia in [questa mappa](https://experience.arcgis.com/experience/0a5dfcc103d0468bbb6b14e713ec1e30/)

Sarebbe bello se li potessi integrare nel bot

**Comment by aborruso** [comment]
Purtroppo hanno da ieri smesso di aggiornarli :( (quelli comunali).
Quindi non vale la pena

**Comment by nelsonmau** [comment]
@aborruso ma io qui li vedo aggiornati a ieri sera 15/3 h19... https://experience.arcgis.com/experience/0a5dfcc103d0468bbb6b14e713ec1e30/

**Comment by nelsonmau** [comment]
@aborruso sorry, mi sa che hai ragione: diciamo che i dati per comune sembra che siano stati "oscurati"

**Comment by aborruso** [comment]
@nelsonmau "oscurati" lo sono da ancora prima. Da ieri non aggiornano più nemmeno i servizi relativi che si trovano [qui](https://services1.arcgis.com/XannvQVnsM1hoZyv/ArcGIS/rest/services).

**Comment by floatingpurr** [comment]
Ciao Ragazzi, non sapevo di queste fonti dati. Un peccato però che non siano stabili :( Grazie lo stesso per la segnalazione
