### ISSUE TITLE
Nuovi casi: "mostrami i prossimi 25..."

### ISSUE THREAD

**Issue by nelsonmau** [floatingpurr/covid-19_ita_bot#10]
in questo caso il sistema mi dà i primi 25 (1-25). 

non c'è modo di dirgli "mostrami i successivi 25 (26-50)"

![2020 03 29-web telegram org- ScreenShot](https://user-images.githubusercontent.com/1769578/77855884-b07a0600-71f3-11ea-9e96-a918de9f7951.png)

**Comment by floatingpurr** [comment]
Usa sorta di cursore insomma. Ok ci penso. : )

**Comment by floatingpurr** [comment]
Fatto! : )
