### ISSUE TITLE
Aggiungere il dato sui tamponi

### ISSUE THREAD

**Issue by nelsonmau** [floatingpurr/covid-19_ita_bot#13]
non mi odiare :-)

già dal messaggio di welcome metterei i tamponi, va bene anche il solo aggregato nazionale

[io lo vedo qui](https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv) tra le ultime colonne

**Comment by floatingpurr** [comment]
Ciao! Ma perché dovrei, anzi mi fa molto piacere ricevere consigli :) 

Il motivo per cui non li ho messi è che mi pareva un numero che confondente (e.g., casi testati vs. test effettuati, si tratta dei tamponi relativi ai nuovi casi oppure no, etc...). Tu che ne dici?

**Comment by nelsonmau** [comment]
In generale tutti i dati rischiano di essere fuorvianti https://pagellapolitica.it/blog/show/792/perch%C3%A9-i-dati-di-oggi-sullepidemia-non-sono-davvero-di-oggi

**Comment by floatingpurr** [comment]
Certamente 👍 

Mi fai un esempio di come ti aspetteresti il messaggio? Inseriresti il dato dei tamponi o il dato dei casi testati?

Devo trovare un modo semplice per inserire poche info, ma rilevanti, senza complicare troppo la lettura. Credo che il bot possa funzionare bene per questo genere di consultazioni

**Comment by nelsonmau** [comment]
direi nel welcome msg, che ora è così

  Positivi:  60.134 (+1.231)
    Guariti: 234.099 (+1.418)
   Deceduti:  36.030 (   +28)
  Tot. Casi: 330.263 (+2.677)

e invece potrebbe essere così:

**Tamponi effettuati: XXX (+/- YYYY)**
  Positivi:  60.134 (+1.231)
    Guariti: 234.099 (+1.418)
   Deceduti:  36.030 (   +28)
  Tot. Casi: 330.263 (+2.677)

**Comment by floatingpurr** [comment]
Attualmente quella tabellina cuba a Tot. Casi, che è la somma delle prime tre voci. Dovrei mettere il dato sui tamponi altrove.

Ci penso e vedo di studiarmi qualcosa. Grazie ancora per il consiglio! 👍

**Comment by nelsonmau** [comment]
molto bene con i tamponi, MI PIASCE!

![tenor](https://user-images.githubusercontent.com/1769578/95839003-c2ac3380-0d42-11eb-918c-b5e9371dd681.gif)
![tenor (1)](https://user-images.githubusercontent.com/1769578/95839005-c3dd6080-0d42-11eb-9e44-ee2ff49b114c.gif)

**Comment by floatingpurr** [comment]
Ok ottimo! 🎉

Ora devo "solamente" riprogettare l'architettura del bot (#11) e poi possiamo introdurre anche feature più arzigogolate (e.g., #12) :)

Ad essere sincero, non ho però previsioni né sul **se** né sul **quando**
