### ISSUE TITLE
/nuovi per provincia

### ISSUE THREAD

**Issue by nelsonmau** [floatingpurr/covid-19_ita_bot#2]
Il bot permette di vedere i nuovi casi per regione con il comando `/nuovi`

```
Lombardia   +984
Emilia Romagna   +392
Marche   +224
Piemonte   +216
...
```

sarebbe bello poterli vedere anche per provincia, ad esempio (con dati finti):

```
Milano   +20
Roma   +15
Torino  +10
Napoli   +5
...
```

**Comment by floatingpurr** [comment]
Ciao @nelsonmau grazie per il consiglio. Ok posso provare a mettere una funzionalità simile per le top `n` province, con `n=20` o giù di lì. Metterle tutte le province italiane produrrebbe un messaggio troppo lungo.

Un piccolo caveat: ho chiamato il comando /nuovi ma è fuorviante. Difatti ritorna non i nuovi casi, ma la variazione degli attualmente positivi rispetto al giorno prima. Potrei cogliere la palla al balzo per chiamare questi comandi in altro modo

**Comment by floatingpurr** [comment]
Ciao Ragazzi, datemi un po' di tempo. Vi aggiorno ASAP su questa proposta : )

**Comment by floatingpurr** [comment]
Eccomi! Dunque, ho guardato con calma i dati.

Non riesco a tirare fuori il dato equivalente a `/nuovi` con un dettaglio provinciale. Questo perché nel dataset gli attualmente positivi non sono tracciati a livello provinciale, ma solo nazionale e regionale.

A livello provinciale, si potrebbero inferire la variazione dei casi totali, ma questo dato non sarebbe consistente col dato regionale. Difatti, a livello regionale, il bot ritorna il delta degli attualmente positivi (che è un dato importante), mentre a livello provinciale ritornerebbe il delta dei casi totali.

Eventualmente potrei tenere `/nuovi` com’è e  fare altri due comandi per presentare il delta casi totali a livello regionale e provinciale.

Vista l’ora, spero di essermi spiegato bene :)

Ci rifletto. Si accettano consigli!
