### ISSUE TITLE
Altri numeri: deceduti e guariti

### ISSUE THREAD

**Issue by nelsonmau** [floatingpurr/covid-19_ita_bot#9]
secondo me semplicemente a valle: quanto chiudo al bot un territorio, esempio `Lombardia` oppure `Milano`, il bot mi risponde con anche:
- stats deceduti
- stats guariti

(lo so che non è semplice, ma se per caso ti viene l'insonnia... :-) )

**Comment by floatingpurr** [comment]
Questi due numeri sono presentati a livello nazionale e regionale. Purtroppo a [livello provinciale](https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-json/dpc-covid19-ita-province.json) non sono disponibili

**Comment by floatingpurr** [comment]
Per adesso chiudo in attesa di nuovi dati!
